[packages.core]
# nvm! Not via brew, install sh file
casks = ["1password-cli", "wezterm"]
brews = [
	"jq",
	"yq",
  "fd",
	"fzf",
  "ripgrep",
  "chezmoi",
	"terraform",
	"vim",
	"neovim",
	"pnpm",
]

[packages.home]
casks = []
brews = []

[packages.work]
casks = []
brews = [
	"docker",
	"docker-completion",
	"colima",
	"saml2aws",
	"iamlive",
]
