[packages.core]
# chezmoi is installed in setup
casks = ["1password-cli", "wezterm", "obsidian"]
brews = [
	"jq",
	"yq",
	"fd",
	"fzf",
  "bat",
	"ripgrep",
	"zsh",
  "nvm",
	"terraform",
	"vim",
	"neovim",
	"pnpm",
]

[packages.home]
casks = []
brews = []

[packages.work]
brews = ["docker", "docker-completion", "colima", "saml2aws"], #"iamlive"]casks = []
