[packages.core]
# chezmoi is installed in setup
# curl -sSL $url | sh -
curl = [
  # "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh", # nvm
  # "https://get.pnpm.io/install.sh", # pnpm
]
# apt and snap only used on ARM64 Linux (Raspberry Pi)
apt = ["fzf", "bat", "tmux", "zsh"]
snap = ["yq", "nvim"]

[packages.home]
# curl = []
# apt = []
# snap = []

[packages.work]
# curl = []
# apt = []
# snap = []
