[packages.core]
# chezmoi is installed in setup
casks = ["1password-cli", "wezterm", "ghostty", "obsidian"]
# curl = [
#  nvm = curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
#  pnpm = curl -fsSL https://get.pnpm.io/install.sh | sh -
#]
# apt and snap only used on ARM64 Linux (Raspberry Pi)
apt = ["fzf", "bat", "zsh"]
snap = ["yq", "nvim"]
brews = [
  "jq",
  "yq",
  "fd",
  "fzf",
  "bat",
  "ripgrep",
  "zsh",
  "nvm",
  "terraform",
  "vim",
  "neovim",
  "pnpm",
]

[packages.home]
# casks = []
# curl = []
# apt = []
# snap = []
# brews = []

[packages.work]
# casks = []
# curl = []
# apt = []
# snap = []
brews = [
  "awscli",
  "aws-sam-cli",
  "docker",
  "docker-completion",
  "colima",
  "saml2aws",
  #"iamlive",
]
