[packages.core]
# nvm! Not via brew, install sh file
casks = ["1password-cli", "wezterm"]
brews = [
  "jq",
  "yq",
  "fd",
  "fzf",
  "bat",
  "ripgrep",
  "terraform",
  "vim",
  "neovim",
  "pnpm",
]

[packages.home]
casks = []
brews = []

[packages.work]
brews = ["docker", "docker-completion", "colima", "saml2aws"], #"iamlive"]casks = []
