[packages.core]
# nvm! Not via brew, install sh file
casks = ["1password-cli", "wezterm"]
<<<<<<< Updated upstream
brews = [
	"jq",
	"yq",
  "fd",
	"fzf",
  "ripgrep",
  "chezmoi",
	"terraform",
	"vim",
	"neovim",
	"pnpm",
]
=======
brews = ["jq", "yq", "fzf", "bat", "terraform", "vim", "neovim", "pnpm"]
>>>>>>> Stashed changes

[packages.home]
casks = []
brews = []

[packages.work]
casks = []
brews = ["docker", "docker-completion", "colima", "saml2aws", "iamlive"]
